"""add coluna descricao

Revision ID: 7108f30727c8
Revises: 2ea20bbf43cf
Create Date: 2026-04-07 16:24:14.515396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7108f30727c8'
down_revision: Union[str, Sequence[str], None] = '2ea20bbf43cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descriacao', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'descriacao')
    # ### end Alembic commands ###
